use std::io::{self, BufRead, Write};

use sharo_core::protocol::{
    PrePromptComposeHookInput, RecollectionCard, RecollectionCardKind, RecollectionCardState,
    RecollectionPayload, ToolCallRequest, ToolCallResponse,
    validate_pre_prompt_compose_input_value,
};
use sharo_hazel_mcp::normalize::normalize_recollection_output;

fn synthesize_recollection(input: &PrePromptComposeHookInput) -> RecollectionPayload {
    let kind = input
        .card_policy_hints
        .first()
        .map(|hint| hint.kind.clone())
        .unwrap_or(RecollectionCardKind::AssociationCue);
    let card_policy_ids = input
        .card_policy_hints
        .first()
        .map(|hint| hint.policy_ids.clone())
        .unwrap_or_else(|| input.policy_ids.clone());
    RecollectionPayload {
        policy_ids: input.policy_ids.clone(),
        cards: vec![RecollectionCard {
            card_id: format!("hazel-{}-{}", input.task_id, input.session_id),
            kind,
            state: RecollectionCardState::Candidate,
            subject: "pre_prompt_recollection".to_string(),
            text: format!("Prior context likely relevant to goal: {}", input.goal),
            provenance: vec![sharo_core::protocol::ProvenanceRef {
                source_ref: "hazel:recollect".to_string(),
                source_excerpt: Some("generated by hazel mcp wrapper".to_string()),
            }],
            policy_ids: card_policy_ids,
        }],
    }
}

fn main() {
    let stdin = io::stdin();
    let mut stdout = io::stdout();
    for line in stdin.lock().lines() {
        let Ok(line) = line else {
            break;
        };
        if line.trim().is_empty() {
            continue;
        }
        let response = match serde_json::from_str::<ToolCallRequest>(&line) {
            Ok(call) => {
                if call.tool != "hazel.recollect" {
                    ToolCallResponse {
                        ok: false,
                        output: None,
                        error: Some(format!("unsupported_tool tool={}", call.tool)),
                    }
                } else {
                    match validate_pre_prompt_compose_input_value(&call.input) {
                        Ok(input) => {
                            let output = synthesize_recollection(&input);
                            let output_value = serde_json::to_value(output)
                                .expect("serialize recollection payload");
                            match normalize_recollection_output(&output_value) {
                                Ok(validated) => ToolCallResponse {
                                    ok: true,
                                    output: Some(
                                        serde_json::to_value(validated)
                                            .expect("serialize validated recollection"),
                                    ),
                                    error: None,
                                },
                                Err(error) => ToolCallResponse {
                                    ok: false,
                                    output: None,
                                    error: Some(error),
                                },
                            }
                        }
                        Err(error) => ToolCallResponse {
                            ok: false,
                            output: None,
                            error: Some(error),
                        },
                    }
                }
            }
            Err(error) => ToolCallResponse {
                ok: false,
                output: None,
                error: Some(format!("invalid_json error={error}")),
            },
        };
        let payload = serde_json::to_string(&response).expect("serialize tool response");
        let _ = writeln!(stdout, "{payload}");
        let _ = stdout.flush();
    }
}
